spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-spring-consumer
      enable-auto-commit: true
      auto-offset-reset: earliest # indicates that kafka will consume messages posted on topic before application is started. The default is latest